/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import backend.svg.SvgBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SvgBuilder.createImage();
    }
}
